[package]
name = "lazy_hash"
version = "0.1.0"
edition = "2021"
[dependencies.base64]
version = "0.13.0"
[dependencies.bcrypt]
version = "0.13.0"
[dependencies.uuid]
version = "1.1.2"
features = ["v4"]
